"""boxes table

Revision ID: 62eae8cfbb30
Revises: 334031fa561d
Create Date: 2020-02-29 16:10:24.176534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62eae8cfbb30'
down_revision = '334031fa561d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxes',
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('is_full', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.PrimaryKeyConstraint('box_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boxes')
    # ### end Alembic commands ###
