"""buildings table

Revision ID: d3ac4635e5e0
Revises: 
Create Date: 2020-02-29 16:07:10.910458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ac4635e5e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('box_num', sa.Integer(), nullable=True),
    sa.Column('people_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('building_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buildings')
    # ### end Alembic commands ###
